variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - if [ ! -z "${CI_COMMIT_SHA}" ]; then export APP_VERSION="${CI_COMMIT_SHA:0:8}"; fi
  - if [ ! -z "${CI_COMMIT_TAG}" ]; then export APP_VERSION="${CI_COMMIT_TAG}"; fi

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test

test:
  stage: test
  image: gaoermai/docker:18.09.8-openjdk11-001
  services:
    - docker:18.09.8-dind
  script:
    - IP=$(bash env/setup_docker.sh docker)
    - echo $IP
    - cat /etc/hosts
    - export RUNNING_CODE_IP=$(hostname -i)
    - echo $RUNNING_CODE_IP
    - cd env && ./dc_pc up -d && cd ..
    - ./gradlew run

